char *bi_commands[];
int (*bi_functions[]) (char **);
char * redirects[];
int numRedirs();
int num_BI ();
int my_cd(char **args);
int my_exit(char **args);
int my_help(char **args);
int count (char *line, char * delim);
char * get_line();
char ** split_line(char *line, char * delim);
char ** delete_spaces (char ** args);
static void sighandler(int signo);
int run_redirect(char *file, int *newfd, int fd2);
int run_pip(char* input, char* output);
int run_builtin (char ** c);
int run_nonbuiltin (char ** c);
int run_special(char * line);
int execute(char ** args, int num);
int command_loop();
int main(int argc, char **argv);
